[package]
name = "awscli-mfa"
version = "0.1.0"
edition = "2021"
authors = ["Kanji Tanaka <sumireminami@gmail.com>"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
dirs = "4.0"
lazy_static = "1.4"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

[dependencies.otp]

git = "https://github.com/TimDumol/rust-otp"
