[package]
name = "awscli-mfa"
version = "0.1.0"
edition = "2021"
authors = ["Kanji Tanaka <sumireminami@gmail.com>"]

[dependencies]
anyhow = "1.0"
aws-config = "0.54.1"
aws-sdk-sts = "0.24.0"
clap = { version = "4.1", features = ["derive"] }
cli-clipboard = "0.4"
dirs = "4.0"
lazy_static = "1.4"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }

[dependencies.otp]

git = "https://github.com/TimDumol/rust-otp"
